#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")" || exit
clang-format -i ./*.c ./*.h
clang \
	-Wall \
	-Wextra \
	-Wpedantic \
	-Wconversion \
	-Wimplicit-fallthrough \
	-Wmissing-prototypes \
	-Wshadow \
	-Wstrict-prototypes \
	-fsanitize=address,undefined \
	-g \
	-o "ceramic" \
	"main.c"
